### ISSUE TITLE
Max Length and Auto-Validate

### ISSUE THREAD

**Issue by chapmacl** [vanshg395/intl_phone_field#15] opened 2020-08-05 08:12 UTC
The maximum length as a default is set to 10, however many international phone numbers are longer than 10 digits. The auto-validate method then just checks if the phone number is less than 10 digits (not max length, just the number 10). This should vary depending on the country code and be automatically updated

**Comment by vanshg395** [comment] 2020-08-05 08:55
Duplicate of #12

**Closed by vanshg395** 2020-08-05 08:55 UTC

**Comment by chapmacl** [comment] 2020-08-05 09:03
I have a German mobile number which is 11 digits long (not including +49), but obviously my US mobile number follows the 10 digit rule. If I want to create an app with an international audience, then this is clearly an issue. I like the look and functionality of this, but this is a feature that is definitely lacking

**Comment by zmeggyesi** [comment] 2021-05-07 04:44
@chapmacl There is a fix for it now, though its _flexibility_ still leaves something to be desired...
